/**
 * Supabase Database Types — Placeholder
 *
 * This file is auto-generated by the Supabase CLI.
 * Run `/sync-db` to replace this with your real schema types.
 *
 * Command:
 *   supabase gen types typescript --project-id <PROJECT_ID> --schema public > src/types/supabase.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
